# Generated by Django 3.2.9 on 2022-04-18 03:01

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=blog.models.NameField(default='Uncategorised', max_length=255),
        ),
    ]
